# Generated by Django 6.1 on 2026-08-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_business_category_business_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
