# Generated by Django 6.1 on 2026-08-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['appointment'], name='api_review_appoint_5c2c16_idx'),
        ),
    ]
